[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PRACTICE_ID = "shafer-clinic"
NEXT_PUBLIC_PRACTICE_NAME = "Shafer Clinic"
NEXT_PUBLIC_DOCTOR_NAME = "Dr. David Shafer, MD, FACS"
NEXT_PUBLIC_PRACTICE_LOCATION = "535 5th Ave, 33rd Floor, New York, NY 10017"
NEXT_PUBLIC_PRACTICE_PHONE = "(212) 888-7770"
NEXT_PUBLIC_BRAND_PRIMARY = "#1a365d"